services:
  db:
    image: mysql:8.0
    container_name: boloapp_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-boloapp}
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: boloapp_web
    restart: always
    volumes:
      - ./app:/app/app
      - profile_photos:/app/app/static/uploads/profile_photos
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - DB_NAME=${DB_NAME:-boloapp}
      - SECRET_KEY=${SECRET_KEY:-desenvolvimento_boloapp_arthur_neves}
    depends_on:
      - db

  nginx:
    image: nginx:1.21-alpine
    container_name: boloapp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/app/static:ro
      - profile_photos:/app/app/static/uploads/profile_photos:ro
    depends_on:
      - web

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run 2d344f28-911c-445e-8bef-9ca28c00fb5e
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - nginx

volumes:
  mysql_data:
  profile_photos:
